/*
 * This file is generated by jOOQ.
 */
package com.example.read;


import com.example.read.tables.CustomerSummary;
import com.example.read.tables.Projections;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customer_summary</code>.
     */
    public static final CustomerSummary CUSTOMER_SUMMARY = CustomerSummary.CUSTOMER_SUMMARY;

    /**
     * The table <code>public.projections</code>.
     */
    public static final Projections PROJECTIONS = Projections.PROJECTIONS;
}
